name: Tracker Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Startup test database machine
        run: sudo service mysql start
      - name: Create test database
        run: |
          mysql -uroot -proot < db-migrations/tracker-migration/databases/mysql/create_databases_mysql.sql
      - name: Build test, and run test tracker migration with Gradle
        run: ./gradlew :db-migrations:tracker-migration:build
      - name: Build and test tracker with Gradle
        run: ./gradlew :applications:tracker:build
      - name: Publish tracker-migration artifact
        uses: actions/upload-artifact@v1
        with:
          name: tracker-migration
          path: db-migrations/tracker-migration/build/libs/tracker-migration.jar
      - name: Publish tracker artifact
        uses: actions/upload-artifact@v1
        with:
          name: tracker
          path: applications/tracker/build/libs/tracker.jar
  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Cf Cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf-cli
      - name: Download tracker-migration artifact
        uses: actions/download-artifact@v1
        with:
          name: tracker-migration
      - name: Download tracker artifact
        uses: actions/download-artifact@v1
        with:
          name: tracker
      - name: Deploy to cf
        run: |
          cf api "$CF_API_URL"
          cf auth
          cf target -o "$CF_ORG" -s "$CF_SPACE"
          cf push tracker-migration -p ./tracker-migration/tracker-migration.jar -f deployments/cf/review/manifest.yml
          cf push tracker -p ./tracker-migration/tracker-migration.jar -f deployments/cf/review/manifest.yml
        env:
          CF_API_URL: ${{ secrets.CF_API_URL }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}